/*
 * generated by Xtext 2.23.0
 */
package de.seronet_projekt.ros.interfaces.pool.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class RosInterfacesPoolProposalProvider extends AbstractRosInterfacesPoolProposalProvider {
}
