/*
 * generated by Xtext 2.23.0
 */
package de.seronet_projekt.ros.interfaces.pool.ide


/**
 * Use this class to register ide components.
 */
class RosInterfacesPoolIdeModule extends AbstractRosInterfacesPoolIdeModule {
}
